version: '3'
services:
    php-apache:
        container_name: letsfly_apache
        # image: php:7.2-apache
        image: letsfly_apache
        ports:
            - 888:80
        volumes:
            - D:/repos/letsfly:/var/www/html
        links:
            - 'mariadb'

    adminer:
        container_name: letsfly_adminer
        image: adminer
        restart: always
        ports:
          - 777:8080

    mariadb:
        container_name: letsfly_mariadb
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'

volumes:
    mariadb: